name: build
     on: [push, pull_request]
     jobs:
       build:
         runs-on: ${{ matrix.os }}
         strategy:
           fail-fast: false
           matrix:
             os: [windows-latest]
             build_type: [Release]
             enable_ui: [on]
             include:
               - os: windows-latest
                 build_type: Release
                 enable_ui: on
         steps:
         - uses: actions/checkout@v3
           with:
             submodules: 'recursive'
         - name: 安装依赖
           shell: bash
           run: |
             # Windows环境下安装7z用于解压Skia库
             if [[ "${{ runner.os }}" == "Windows" ]] ; then
               choco install 7zip
             fi
         - name: 下载并配置Skia库
           run: |
             curl -L https://github.com/blueloveTH/aseprite/releases/download/v0.01/skia.zip --output skia.zip
             7z x skia.zip -o./skia
         - name: 生成构建文件
           run: |
             cmake -S . -B build -G Ninja \
               -DCMAKE_BUILD_TYPE=Release \
               -DENABLE_UI=ON \
               -DLAF_BACKEND=skia \
               -DSKIA_DIR=./skia \
               -DSKIA_LIBRARY_DIR=./skia/out/Release-x64
         - name: 编译
           run: |
             cd build && ninja
         - uses: actions/upload-artifact@v3
           with:
             name: aseprite
             path: |
               build/bin/aseprite.exe
               build/bin/data
