name: Build Aseprite (Linux) - Artifact Only

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  

env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    name: Build & Package Aseprite (Linux)
    runs-on: ubuntu-latest
    permissions:
      contents: read 
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        shell: bash
        run: |
          # Linux 依赖安装（使用 apt）
          sudo apt-get update -qq
          sudo apt-get install -y \
            wget p7zip-full \
            libpixman-1-dev libfreetype6-dev libharfbuzz-dev zlib1g-dev \
            libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev

      - name: Install Skia
        shell: bash
        run: |
          # 下载适用于 Linux x64 的 Skia 库
          wget https://github.com/aseprite/skia/releases/download/m124-08a5439a6b/Skia-Linux-Release-x64.zip
          unzip Skia-Linux-Release-x64.zip -d skia

      - uses: aseprite/get-ninja@main 

      - name: Generate Build Files
        shell: bash
        run: |
          export enable_ccache=on  # Linux 支持 ccache 加速构建
          export laf_backend=skia
          export enable_scripting=on
          export skia_arch=x64  # Linux 主流为 x64 架构

          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DENABLE_TESTS=OFF \
            -DENABLE_SCRIPTING=$enable_scripting \
            -DENABLE_CCACHE=$enable_ccache \
            -DLAF_BACKEND=$laf_backend \
            -DSKIA_DIR=$(realpath skia) \
            -DSKIA_LIBRARY_DIR=$(realpath skia/out/Release-$skia_arch)

      - name: Compile Aseprite
        shell: bash
        run: cd build && ninja

      - name: Verify Build Output
        shell: bash
        run: |
          if [[ ! -d "build/bin" ]]; then
            echo "Error: Build output directory not found!"
            exit 1
          fi
          if [[ ! -f "build/bin/aseprite" ]]; then
            echo "Error: aseprite executable not found in build output!"
            exit 1
          fi
          ls -la build/bin

      - name: Clean & Prepare Portable Package
        working-directory: build/bin
        shell: bash
        run: |
          find . -mindepth 1 ! \( -name 'aseprite' -o -name 'data' -prune \) -exec rm -rf {} +
          echo '# Portable mode' > aseprite.ini

      - name: Package as Zip
        working-directory: build/bin
        shell: bash
        run: |
          TIMESTAMP=$(date +%Y%m%d-%H%M%S)
          7z -tzip a "Aseprite-Linux-${TIMESTAMP}.zip" *

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Aseprite-Linux-Build
          path: build/bin/Aseprite-Linux-*.zip
          retention-days: 30
          if-no-files-found: error 

