name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - run: choco install 7zip -y
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: ilammy/msvc-dev-cmd@v1
    - shell: cmd
      run: |
        curl -L https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip -o skia.zip
        curl -L https://slproweb.com/download/Win64OpenSSL-1_1_1w.exe -o openssl.exe
        dir skia.zip || exit 1 # 检查 skia.zip 是否下载成功
        openssl.exe /SILENT /DIR="openssl_install"
        copy openssl_install\libcrypto-1_1-x64.dll .
        7z x skia.zip -oskia || exit 1 # 解压到 skia 目录并检查是否成功
    - shell: cmd
      run: |
        dir skia # 检查 skia 目录是否存在
        dir skia\out\Release-x64 # 检查 Release-x64 目录
        dir skia\out\Release-x64\skia.lib # 检查 skia.lib 是否存在
    - shell: bash
      run: |
        export enable_ccache=off
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DENABLE_UI=on \
          -DENABLE_CCACHE=$enable_ccache \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=./skia \
          -DSKIA_LIBRARY_DIR=./skia/out/Release-x64 \
          -DSKIA_LIBRARY=./skia/out/Release-x64/skia.lib
    - shell: bash
      run: |
        cd build && ninja
    - shell: cmd
      run: |
        dir libcrypto-1_1-x64.dll
        dir build\bin\data
        dir build\bin\aseprite.exe
    - uses: actions/upload-artifact@v4
      with:
        name: aseprite
        path: |
          libcrypto-1_1-x64.dll
          build/bin/data
          build/bin/aseprite.exe
